name: Docker Image CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1

    - name: decide on tag
      run: |
        image_tag=$(echo $GITHUB_REF | sed -e 's/refs\/heads\///g' -e 's/refs\/tags\///g' | sed -e 's/master/latest/g')
        echo "::debug::decide on image tag ${image_tag}"
        echo "::set-env name=IMAGE_TAG::${image_tag}"
      
    - name: decide on repo
      env:
        DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
      run: |
        repo_name=${DOCKER_REPOSITORY}
        if [ -z "$repo_name" ]; then echo "::set-env name=DOCKER_REPOSITORY::${GITHUB_REPOSITORY}"; fi

    - name: build image
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_REPO:
      run: |
        docker build --tag ${DOCKER_REPOSITORY}:${IMAGE_TAG} .
    
    - name: push image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
      run: |
        echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY}
        docker push ${DOCKER_REPOSITORY}:${IMAGE_TAG}
        docker logout